</main><footer class="site-footer"><div class="footer-intro"><a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="brand-mark" aria-hidden="true">✧</span>glowwise</a><p>Less noise.<br>More you.</p><span>Grooming discovery, with reasons.</span></div><div class="footer-links">
<nav aria-label="Discover"><h2>Discover</h2><?php foreach (['categories'=>'Categories','explore'=>'Explore products','guides'=>'The guides','finder'=>'Product finder','compare'=>'Compare','saved'=>'Your saved list'] as $s=>$n) { echo '<a href="'.esc_url(gw_link($s)).'">'.esc_html($n).'</a>'; } ?></nav>
<nav aria-label="Care categories"><h2>Everyday care</h2><?php foreach (gw_categories() as $s=>$n) { echo '<a href="'.esc_url(gw_link('categories/'.$s)).'">'.esc_html($n).'</a>'; } ?></nav>
<nav aria-label="Glowwise"><h2>Glowwise</h2><?php foreach (['about'=>'About us','how-we-select'=>'How we select','contact'=>'Contact','corrections'=>'Corrections','disclosures'=>'Disclosures','accessibility'=>'Accessibility'] as $s=>$n) { echo '<a href="'.esc_url(gw_link($s)).'">'.esc_html($n).'</a>'; } ?></nav>
<nav aria-label="Your choices"><h2>Your choices</h2><?php foreach (['privacy'=>'Privacy','terms'=>'Terms','cookies-and-storage'=>'Cookies & browser storage','sitemap'=>'Site map'] as $s=>$n) { echo '<a href="'.esc_url(gw_link($s)).'">'.esc_html($n).'</a>'; } ?><button class="text-link js-only" data-cookie-open>Cookie settings</button><noscript><a href="<?php echo esc_url(gw_link('cookies-and-storage')); ?>">Cookie settings information</a></noscript></nav></div><div class="footer-bottom"><span>© <?php echo (int)gmdate('Y'); ?> Glowwise · Published by Imagine Utopia</span><span>Independent research. No checkout. No accounts.</span></div></footer>
<div class="toast" role="status" aria-live="polite" hidden></div>
<aside class="compare-tray js-only" aria-label="Comparison shortlist" hidden><span data-tray-text>Compare your shortlist</span><a class="button" href="<?php echo esc_url(gw_link('compare')); ?>">Compare now <span aria-hidden="true">↗</span></a><button class="small-button" data-compare-clear>Clear</button></aside>
<dialog id="cookie-settings" aria-labelledby="cookie-title"><div class="dialog-top"><p class="eyebrow">Your browser. Your choices.</p><button class="icon-button" data-dialog-close aria-label="Close cookie settings">×</button></div><h2 id="cookie-title">Keep it essential.</h2><p>Saving products and your choices uses storage in this browser. Our contact form uses an essential security cookie. Optional Google Analytics measures page visits and tool use only after you accept. No advertising, contact text or search terms are collected.</p><div class="consent-row"><span><strong>Essential functionality</strong><small>Security, saved products, comparisons and preferences.</small></span><span class="tag">Always available</span></div><div class="consent-row"><label for="analytics-consent"><strong>Optional Google Analytics</strong><small>Off until you accept. Page visits and fixed tool actions help us understand what is useful.</small></label><input id="analytics-consent" type="checkbox" role="switch"></div><div class="actions"><button class="button" data-consent-save>Save choices</button><button class="button secondary" data-consent-reject>Reject optional</button></div><p class="fine"><a href="<?php echo esc_url(gw_link('cookies-and-storage')); ?>">Read about storage and withdrawal</a>. Reopen these settings at any time.</p></dialog>
<aside class="consent-banner js-only" aria-label="Browser storage choices" hidden><div><strong>A little clarity about storage.</strong><p>Essential tools work without analytics. Google Analytics stays off until you accept it in Settings. Rejecting keeps the essential tools available.</p></div><button class="button secondary" data-consent-reject>Reject optional</button><button class="button" data-cookie-open>Settings</button></aside>
<?php wp_footer(); ?></body></html>
