<?php get_header(); ?>
<section class="home-hero"><div class="hero-copy"><p class="eyebrow"><?php echo esc_html(get_theme_mod('gw_hero_kicker','A compass for everyday care')); ?></p><h1><?php $heading=get_theme_mod('gw_hero_heading','Find your kind of good.');echo $heading==='Find your kind of good.'?'Find your kind<br>of <em>good.</em>':esc_html($heading); ?></h1><p class="lede"><?php echo esc_html(get_theme_mod('gw_hero_intro','Grooming that fits your life. Thoughtfully researched products, clear comparisons and a little less guesswork.')); ?></p><div class="actions"><a class="button" href="<?php echo esc_url(gw_link('explore')); ?>">Explore the edit <span aria-hidden="true">↗</span></a><a class="text-link" href="<?php echo esc_url(gw_link('finder')); ?>">Start with what you need <span aria-hidden="true">→</span></a></div><div class="hero-note"><span class="tiny-compass" aria-hidden="true">✧</span><p>For every body. Every routine.<br><strong>No hype required.</strong></p></div></div>
<div class="hero-world" aria-label="An original illustrated compass connecting six grooming categories"><img class="world-art" src="<?php echo esc_url(get_template_directory_uri().'/assets/art/compass-world.svg'); ?>" width="900" height="900" alt=""><div class="orbit-label">Your daily<br><em>orbit.</em></div><?php $i=0;foreach (gw_categories() as $s=>$n) { ?><a class="orbit-link orbit-<?php echo ++$i; ?>" href="<?php echo esc_url(gw_link('categories/'.$s)); ?>"><?php echo esc_html($n); ?><span aria-hidden="true">↗</span></a><?php } ?><button class="motion-control js-only" data-motion-pause aria-pressed="false">Pause motion</button><span class="world-caption">An original Glowwise illustration</span></div>
<div class="hero-bottom"><span>Scroll to discover <span aria-hidden="true">↓</span></span><span>Six categories. One considered routine.</span></div></section>
<section class="manifesto section container"><p class="eyebrow">Small choices. Better understood.</p><h2><?php echo esc_html(get_theme_mod('gw_manifesto_heading','The right choice starts with the right questions.')); ?></h2><p><?php echo esc_html(get_theme_mod('gw_manifesto_intro','What’s in it? Which size fits your budget? What can it actually do? We connect the facts to the things that matter to you.')); ?></p><a class="text-link" href="<?php echo esc_url(gw_link('how-we-select')); ?>">A look behind the edit <span aria-hidden="true">↗</span></a></section>
<section class="section category-section container"><div class="section-heading"><div><p class="eyebrow">Find your starting point</p><h2>A world of everyday care.</h2></div><a class="text-link" href="<?php echo esc_url(gw_link('categories')); ?>">All categories <span aria-hidden="true">↗</span></a></div><div class="category-grid"><?php gw_category_cards(); ?></div></section>
<section class="finder-feature section"><div class="feature-art" aria-hidden="true"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/art/finder-compass.svg'); ?>" width="700" height="700" loading="lazy"><span>01 · Your needs<br>02 · Your budget<br>03 · Your shortlist</span></div><div class="feature-copy"><p class="eyebrow">A little direction, on your terms</p><h2>Less searching.<br><em>More finding.</em></h2><p><?php echo esc_html(get_theme_mod('gw_finder_intro','Tell us what you’re looking for. Our finder narrows the catalog using clear rules—and shows you why each product made the list.')); ?></p><a class="button" href="<?php echo esc_url(gw_link('finder')); ?>">Find your fit <span aria-hidden="true">↗</span></a><p class="fine">No account. No diagnosis. No hidden ranking.</p></div></section>
<section class="section container"><div class="section-heading"><div><p class="eyebrow">From the researched edit</p><h2>Facts first. Possibilities next.</h2></div><a class="text-link" href="<?php echo esc_url(gw_link('explore')); ?>">Explore every product <span aria-hidden="true">↗</span></a></div><div class="product-grid"><?php $catalog=gw_catalog();foreach (['skincare','haircare','fragrance'] as $c) { foreach ($catalog as $p) { if ($p['category']===$c) { gw_product_card($p);break; } } } ?></div></section>
<section class="section journal-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">The field notes</p><h2>Good questions.<br>Considered answers.</h2></div><a class="text-link" href="<?php echo esc_url(gw_link('guides')); ?>">Read all guides <span aria-hidden="true">↗</span></a></div><div class="guide-grid"><?php foreach (get_posts(['post_type'=>'post','post_status'=>'publish','numberposts'=>3,'orderby'=>'title','order'=>'ASC']) as $p) { gw_guide_card($p); } ?></div></div></section>
<section class="trust-strip container section"><div><span>01</span><h3>Sources you can follow.</h3><p>Manufacturer and retailer references, with a check date on every product.</p></div><div><span>02</span><h3>Limits you can see.</h3><p>Unknown facts stay unknown. Research never becomes a claim of hands-on testing.</p></div><div><span>03</span><h3>Your space, respected.</h3><p>Save locally, compare freely, and keep essential tools working without analytics.</p></div></section>
<?php if (trim(get_post_field('post_content',get_queried_object_id()))) { ?><section class="container section prose"><?php while (have_posts()) { the_post();the_content(); } ?></section><?php } get_footer(); ?>
