<?php get_header();while (have_posts()) { the_post();$slug=get_post_field('post_name',get_the_ID()); ?><div class="container section">
<?php gw_intro(in_array($slug,['finder','compare','saved'],true)?'Your everyday toolkit':'Glowwise, considered',get_the_title(),get_the_excerpt()); ?>
<?php if ($slug==='categories') { ?><div class="prose page-copy"><?php the_content(); ?></div><div class="category-grid"><?php gw_category_cards(); ?></div>
<?php } elseif ($slug==='finder') { ?><div class="tool-layout"><aside class="tool-note"><span class="tool-spark" aria-hidden="true">✧</span><h2>A shortlist.<br>With reasons.</h2><p>Select a category, a product type and your preferences. You can skip optional choices.</p><ol><li>Exact category and type matches.</li><li>A checked variant within your item budget.</li><li>Only verified attributes pass an attribute filter.</li><li>Matches stay alphabetical. No paid positions.</li></ol><p class="fine">This tool does not assess skin conditions or predict personal results. An unavailable product may still match; its stock warning remains visible.</p></aside><section class="finder-panel"><p id="finder-progress" class="eyebrow js-only" aria-live="polite">Step 1 of 3</p><?php $prefill=gw_validate_filters(array_intersect_key(wp_unslash($_GET),array_flip(['category','type','max-price','fragrance-free','finish'])));gw_filters(is_wp_error($prefill)?[]:$prefill,true); ?><div id="finder-navigation" class="actions js-only" hidden><button class="button secondary" type="button" data-finder-back>Back</button><button class="small-button" type="button" data-finder-skip>Skip this preference</button><button class="button" type="button" data-finder-next>Continue →</button></div><button class="text-link js-only" type="button" data-finder-restart>Restart finder</button><noscript><p>The complete form above still works. Results open in Explore with your selected filters.</p></noscript></section></div><section id="finder-results" class="section" aria-live="polite" aria-busy="false"></section>
<?php } elseif ($slug==='saved') { ?><div class="prose page-copy"><?php the_content(); ?></div><section id="saved-results" aria-live="polite" aria-busy="false"><div class="empty-state"><span aria-hidden="true">✧</span><h2>Your next good find belongs here.</h2><p>Use Save on any product to keep it in this browser. There’s no account and no sync between devices.</p><a class="button" href="<?php echo esc_url(gw_link('explore')); ?>">Explore the edit ↗</a></div></section><noscript><p class="notice">Browser-local saving needs JavaScript. You can bookmark individual product pages instead.</p></noscript><button class="small-button js-only" data-saved-clear>Remove all saved products</button>
<?php } elseif ($slug==='compare') { ?><div class="prose page-copy"><?php the_content(); ?></div><section id="compare-results" aria-live="polite" aria-busy="false"><div class="empty-state"><span aria-hidden="true">↔</span><h2>Put the useful differences side by side.</h2><p>Select up to three products of the same type. Compare a shampoo with shampoos, or a trimmer with trimmers.</p><a class="button" href="<?php echo esc_url(gw_link('explore')); ?>">Build a shortlist ↗</a></div></section><noscript><p class="notice">The browser comparison shortlist needs JavaScript. Product detail pages contain the same source-checked facts.</p></noscript>
<?php } elseif (in_array($slug,['contact','corrections'],true)) { ?><div class="contact-layout"><div class="prose"><?php the_content(); ?></div><?php get_template_part('parts/contact-form',null,['correction'=>$slug==='corrections']); ?></div>
<?php } elseif ($slug==='sitemap') { ?><div class="prose"><?php the_content(); ?><h2>Discover</h2><ul><?php foreach (['categories'=>'Categories','explore'=>'Explore','guides'=>'Guides','finder'=>'Finder','compare'=>'Compare','saved'=>'Saved'] as $s=>$n) { echo '<li><a href="'.esc_url(gw_link($s)).'">'.esc_html($n).'</a></li>'; } ?></ul><h2>Categories</h2><ul><?php foreach (gw_categories() as $s=>$n) { echo '<li><a href="'.esc_url(gw_link('categories/'.$s)).'">'.esc_html($n).'</a></li>'; } ?></ul><h2>Field notes</h2><ul><?php foreach (get_posts(['post_type'=>'post','post_status'=>'publish','numberposts'=>50]) as $p) { echo '<li><a href="'.esc_url(get_permalink($p)).'">'.esc_html($p->post_title).'</a></li>'; } ?></ul></div>
<?php } else { ?><div class="prose page-copy"><?php the_content(); ?></div><?php if ($slug==='cookies-and-storage') { ?><button class="button js-only" data-cookie-open>Open cookie settings</button><noscript><p>No analytics runs when JavaScript is disabled. Clear this site’s browser data through your browser settings to remove saved items and preferences.</p></noscript><?php } } ?></div><?php }get_footer(); ?>
