"""Compile original editorial copy and researched facts into editable guide HTML."""
from pathlib import Path
import json, html

ROOT = Path(__file__).resolve().parents[1]
products = {p['slug']: p for p in json.loads((ROOT/'content/products.json').read_text(encoding='utf-8'))}
notes = json.loads((ROOT/'content/editorial-product-notes.json').read_text(encoding='utf-8'))['products']
E = html.escape

guides = [
dict(slug='shampoo-for-dry-frizzy-hair', category='haircare', title='Shampoo for dry, frizzy hair: six formulas, different wash-day jobs',
 intro='Compare six checked shampoos by formula, exact pack price and practical trade-offs, with a clear distinction between dry lengths and scalp concerns.',
 opening='A shampoo cleans your scalp; it does not have to solve every problem your lengths have. Dry ends, frizz and an oily scalp can coexist. This edit starts with hydration and conditioning positioning, then separates an active scalp formula and a basic cleansing option so you can see why they are different purchases.',
 selection='The first four are the closest published-information matches to a dry-length or frizz-control brief. Hydrating Factors leads for its verified fragrance-free positioning; Coconut Milk follows for a lower 250 ml price; Avocado & Argan is the explicit frizz-control option; Maleic is the damage-positioned alternative. The active anti-dandruff and basic Beardo products come last because their primary jobs differ. This is a relevance order, not measured frizz reduction.',
 items=['minimalist-hydrating-factors-shampoo','plum-coconut-peptides-shampoo','plum-avocado-argan-shampoo','minimalist-maleic-shampoo','plum-anti-dandruff-shampoo','beardo-no-nonsense-shampoo'],
 education=[('Build a wash-day routine around two different areas','Choose cleansing according to your scalp and use a conditioner appropriate to your hair on the lengths. The American Academy of Dermatology recommends concentrating shampoo on the scalp and adapting conditioning to hair type. If a shampoo leaves your lengths uncomfortable, adding more shampoo or repeatedly washing the ends is not automatically the answer. Decide first whether you are buying a routine cleanser, a conditioning-positioned formula or an active scalp product.'),('Read ingredient labels without turning them into a score','Glycerin, oils, peptides and conditioning polymers tell you what a brand has put into a formula. Their presence does not let us calculate the softness you will experience. “Sulphate-free” describes an excluded ingredient family; it does not establish that a shampoo is universally mild. Fragrance-free information can be useful when you already avoid fragrance, but does not rule out sensitivity to other ingredients.'),('Choose the pack after choosing the job','Compare 250 ml bottles with other 250 ml bottles before deciding on value. Maleic’s 100 ml pack costs less upfront than its 250 ml pack, but the smaller pack has a different cost per volume. A larger bottle saves money only if you actually use it. Do not buy a 750 ml bottle solely because the unit calculation looks attractive when you have never tried the formula.')],
 faqs=[('Will shampoo alone remove frizz?','We cannot promise that. Handling, conditioning, texture and weather affect the result. These recommendations identify different published formula positions; they do not predict your finish.'),('Should I choose the anti-dandruff option for ordinary dryness?','Not automatically. Its salicylic acid and piroctone olamine positioning targets a different scalp concern. Continuing itch, flaking or hair loss deserves qualified advice rather than a shopping diagnosis.'),('Which has a verified fragrance-free label?','Minimalist Hydrating Factors is verified fragrance-free here. Read each current full label; fragrance status is not inferred from a product name or a “natural” claim.')],
 reference='https://www.aad.org/public/everyday-care/hair-scalp-care/hair/healthy-hair-tips', reference_label='AAD: healthy hair tips'),
dict(slug='sunscreen-for-oily-skin', category='skincare', title='Sunscreen for oily skin: six choices by finish, pack and budget',
 intro='A researched sunscreen shortlist for matte, fluid, dewy and tinted preferences, with exact SPF labels, checked pack prices and honest limitations.',
 opening='The most useful sunscreen is one you can apply correctly and keep using. For oily skin, finish can make that routine easier: a specifically matte gel, a natural-finish fluid and a dewy formula are different propositions. We compare those propositions rather than declaring one texture right for every oily face.',
 selection='Plum Green Tea & Zinc leads for its explicit super-matte positioning, then Light Fluid for a natural-finish fluid. Minimalist SPF 50 is the lower first-purchase option. Rice Water serves a dewy preference; SPF 60 serves the higher-label preference; the tinted formula is conditional on shade suitability. All protection labels and finish statements are manufacturer information. We have not performed UV, oil-control or wear testing.',
 items=['plum-green-tea-zinc-spf-50','minimalist-light-fluid-spf-50','minimalist-spf-50','plum-rice-water-spf-50','minimalist-spf-60','plum-sheer-tinted-spf-50'],
 education=[('Protection and finish are separate decisions','SPF describes a protection label, while matte or dewy describes a finish claim. A higher SPF number does not tell you that a product controls shine better. PA++++ is the stated UVA label on these records, rather than a Glowwise laboratory finding. Check the complete pack for directions and water-resistance information instead of interpreting a product’s “sweatproof” marketing as permission to skip reapplication.'),('Application still matters','AAD guidance recommends broad-spectrum SPF 30 or higher, appropriate water resistance and reapplication outdoors about every two hours, and after swimming or sweating. Follow the current pack’s instructions. Sunscreen is one part of protection alongside shade and clothing. Choosing a more expensive bottle or a higher number does not remove the need to apply it properly.'),('Avoid a misleading value comparison','Some packs are measured in grams and others in millilitres. We do not treat those units as interchangeable or convert a fluid into a gram price without a verified density. Compare like units and remember that a 30 g trial pack can cost less to buy while a 100 g pack costs less per gram. For a tint, shade suitability comes before saving a few rupees.')],
 faqs=[('Is a matte label proof that it will suit acne-prone skin?','No. Matte describes the brand’s finish positioning. A non-comedogenic claim is not a guarantee against breakouts, and this guide does not diagnose or treat acne.'),('Should oily skin avoid a dewy formula?','That is a preference, not a universal rule. Rice Water is here as an explicit alternative for readers who enjoy a dewy finish, rather than a hidden recommendation for shine control.'),('Does the photographed carton show every Rice Water pack?','No. Glowwise has a licensed photograph of the 50 g outer carton only. The 30 g and 80 g options retain clearly disclosed image fallbacks; pack facts are stated separately.')],
 reference='https://www.aad.org/public/everyday-care/sun-protection/shade-clothing-sunscreen/how-to-apply-sunscreen', reference_label='AAD: how to apply sunscreen'),
dict(slug='body-lotion-for-dry-skin', category='bodycare', title='Body lotion for dry skin: six choices from fragrance-free to scented',
 intro='Compare one verified fragrance-free lotion and five distinct scented formulas, with exact packs, checked INR prices and practical buying guidance.',
 opening='Start with what makes you use a body lotion consistently: a comfortable texture, a tolerable ingredient list and, if you want it, a scent. This edit puts a verified fragrance-free option first and treats the scented lotions as different preferences, not interchangeable claims of superior hydration.',
 selection='Minimalist leads for verified fragrance-free status. Among the scented 400 ml options, Caramello has the lowest checked price; Tropic and Hazelnut follow at the same price with different texture and scent stories. Hawaiian Rumba and Vanilla Vibes cost more at this observation. That order makes cost and tolerance visible; it does not rank measured moisturisation or firming.',
 items=['minimalist-niacinamide-body-lotion','plum-vanilla-caramello-lotion','plum-tropic-lotion','plum-hazelnut-lotion','plum-hawaiian-rumba-lotion','plum-vanilla-vibes-lotion'],
 education=[('Use comfort and tolerance as the first filter','A fragrant lotion may be enjoyable, but scent is optional. If fragrance is something you avoid, start with the verified fragrance-free record rather than relying on a food-inspired name or a “natural” story. Niacinamide, shea butter, glycerin and named oils are formulation facts where verified; they do not let us promise relief from a diagnosed skin condition.'),('Make application part of a simple routine','AAD dry-skin guidance recommends applying moisturiser after washing while skin remains damp and choosing gentle care. Persistent cracking, bleeding or discomfort is a reason to seek qualified advice. We do not prescribe treatment from a product card. A lotion’s marketing around firmness or glow is separate from the ordinary task of moisturising.'),('Compare scented choices honestly','Caramello, Vanilla Vibes and Hazelnut are not the same scent merely because all sound gourmand. Hawaiian Rumba has a fruity floral direction; Tropic is a separate gel-cream positioning. The manufacturer’s scent descriptions help you shortlist, but no online note list can tell you whether you will enjoy a fragrance on your skin. Prefer a manageable first purchase over a multi-bottle bundle.')],
 faqs=[('Which option is cheapest?','Among the checked 400 ml bottles, Caramello is ₹385. Minimalist is ₹269 for 180 g, which is a different quantity and unit. We do not call it cheaper per millilitre.'),('Is Tropic’s firming claim independently established here?','No. We record its named ingredients and brand positioning, without measuring firmness or converting marketing into a result.'),('Can I buy Caramello’s smaller bottle?','The 200 ml listing was out of stock at this check. Its displayed price remains a dated reference, not an available offer.')],
 reference='https://www.aad.org/public/everyday-care/skin-care-basics/dry/dermatologists-tips-relieve-dry-skin', reference_label='AAD: dry-skin care'),
dict(slug='perfumes-under-1000', category='fragrance', title='Perfumes under ₹1,000: six SKINN 20 ml scents, with real differences',
 intro='Six identified 20 ml eau de parfum variants compared by published note pyramids, checked price and current stock, without invented longevity claims.',
 opening='At this budget, this is a deliberately narrow comparison: six SKINN eau de parfum families in 20 ml packs. It is not a claim to have tested every perfume sold in India. A small bottle lowers the purchase commitment, while the published note pyramid helps identify a direction you would like to investigate.',
 selection='Raw opens the edit as a fresh direction, followed by Celeste’s fruity floral, Sheer’s softer floral and Nude’s rose-led direction. Steele is the warmer spicy alternative and could be first if that is your preference. Verge is last because its current 20 ml page says Coming Back Soon. This preference-led order is not a projection, wear-time or universal “best perfume” ranking.',
 items=['skinn-raw-20ml','skinn-celeste-20ml','skinn-sheer-20ml','skinn-nude-20ml','skinn-steele-20ml','skinn-verge-20ml'],
 education=[('Read a note pyramid as a description','Top, heart and base notes describe the brand’s intended progression. They are not a complete ingredient list and do not establish how many hours a fragrance lasts. We have not worn these perfumes, compared their projection or tested them in heat. Use the individual product page for the current pyramid; collection copy can be abbreviated or inconsistent.'),('The budget applies to this exact size','The prices here belong to 20 ml bottles. A 50 ml or 100 ml selector on the same manufacturer page is a different purchase. Conditional coupons, delivery and bundles are excluded. Raw and Steele are ₹596 at this check; Celeste, Sheer and Nude show ₹556. Verge’s ₹556 is a collection reference while its current direct page has no active purchase price.'),('Try before buying when possible','A note that sounds attractive may feel different on a blotter or your skin. If a shop offers a genuine sample, use that opportunity without interpreting a brief first impression as an all-day test. You can also compare the smallest available pack and the retailer’s return policy. An eau de parfum label does not supply an exact concentration percentage or guaranteed longevity.')],
 faqs=[('Are these scents restricted to the gender in the brand title?','The manufacturer’s merchandising labels are recorded, but fragrance preference is personal. Choose by the scent direction you enjoy rather than treating the label as a rule.'),('Why is Verge included when unavailable?','It preserves the approved family and lets readers compare its green woody direction. It is clearly a watchlist entry, not one of the five currently listed purchase options.'),('Why does Sheer’s description differ from some collection copy?','We use the individual product’s pyramid: pear, clementine and pink pepper at the top. We do not combine conflicting snippets into an invented note list.')], reference=None),
dict(slug='trimmers-under-1500', category='grooming-tools', title='Trimmers under ₹1,500: six Vega models, three current purchase options',
 intro='A model-specific comparison of Vega trimmers, checked prices, charging, runtime and cleaning limits, with unavailable models clearly separated.',
 opening='A trimmer decision is easier when the model code, charging connection and cleaning instructions are visible. All six identified models have displayed prices below ₹1,500 at this check, but only three are listed for purchase. The other three remain useful comparisons and watchlist entries, not immediately available recommendations.',
 selection='SmartOne S3 leads for its IPX7 rating, Type-C charging and manufacturer’s 160-minute runtime at ₹1,154. Power P1 follows at ₹1,019 with the same stated runtime but washable blades rather than a verified full-device IPX7 rating. Power Lite is the lower current purchase price at ₹849. TurboLite, SmartOne S2 and TurboOne follow as out-of-stock references. No cutting-speed or battery-life test was performed.',
 items=['vega-smartone-s3','vega-power-p1','vega-power-lite','vega-turbolite','vega-smartone-s2','vega-turboone'],
 education=[('Washable blades are not a waterproof body','The S2 and S3 manufacturer pages state IPX7. The other models’ washable-blade wording does not establish that you can rinse the entire device or immerse it. Read the actual manual and disconnect charging before cleaning as instructed. A cleaning shortcut is not worth relying on a rating belonging to another model.'),('Runtime and charging answer different questions','Runtime is the manufacturer’s stated operating duration, not how fast a device recharges. Power P1 and SmartOne S3 state 160-minute runtime and 90-minute charging. TurboLite states 90 minutes for each. Power Lite and TurboOne have a verified 90-minute runtime here, but we leave charging time unknown rather than copying a figure from a related model. Actual results vary with use and battery condition.'),('Choose controls you will actually use','S3’s three speed settings, travel lock and memory positioning may matter if you travel or share a routine across lengths. Its “AI memory” wording is a brand feature name, not evidence of automated grooming advice. If you only need a basic trim, the lower-priced Power Lite may fit your purchase better. Check the supplied combs and length range on the exact model’s current page before ordering.')],
 faqs=[('Which is the cheapest available model in this edit?','Power Lite at ₹849. TurboLite’s ₹609 is lower but its listing was out of stock, so we do not present that as a purchase you can currently complete.'),('Does titanium prove better trimming?','No. Blade material is a verified specification on SmartOne S2 and S3, not a measured cutting-performance ranking.'),('Can I use a generic family listing?','Check the model code and contents. VHTH-36, VHTH-25 and VHTH-38 are different models; a similar-looking photograph or a shared brand name does not make the specifications interchangeable.')], reference=None),
dict(slug='beard-oil-benefits', category='beard-grooming', title='Beard-oil benefits: what conditioning can do, and six options to compare',
 intro='Understand beard conditioning without growth promises, then compare six real oils by format, named ingredients, exact pack and checked price.',
 opening='Beard oil is an optional grooming step, not proof of new growth. The useful question is whether an oil suits the beard you already have and the skin beneath it. This explanatory guide keeps the conditioning role separate from product names that promise “growth”, then gives six distinct purchasing options.',
 selection='The recommendation sequence starts with Ustraa’s low-cost 35 ml woody option, then Beardo Godfather and The Man Company’s differently positioned 30 ml oils. Beardo’s 50 ml Beard & Hair Oil offers a broader format; Bombay’s 10 ml roll-on is a portability choice; its Onion oil is an ingredient-positioned alternative. This is a format-and-budget sequence, not a growth-efficacy ranking. None was personally tested.',
 items=['ustraa-woody-beard-oil','beardo-godfather-oil','man-company-beard-oil','beardo-beard-hair-oil','bombay-beard-roll-on','bombay-onion-beard-oil'],
 education=[('The benefit is conditioning, not guaranteed growth','AAD beard-care guidance distinguishes care according to the skin beneath the beard: oil for normal or dry skin, beard conditioner for acne-prone skin and gentle moisturiser for sensitive skin. That makes oil one possible format, not a required step for every face. A product’s named plant oils or proprietary complex does not prove it creates follicles or treats patchiness.'),('Match the application format to your routine','A roll-on changes how you dispense and carry a product; it is not a stronger formula simply because it costs less per bottle. A 10 ml roll-on and a 50 ml bottle have very different quantities. Start with the manufacturer’s directions and avoid turning the entire beard greasy to chase a claimed result. Persistent irritation is a reason to stop and seek qualified advice.'),('Read growth language critically','We retain exact names such as Beard Growth Oil so you can identify the real listing. “RootBioTec HO”, onion oil and brand before/after claims are manufacturer information, not independent clinical findings by Glowwise. The Man Company’s current 30 ml storefront lists ₹299; older indexed listings can show a different price. The current variant and check date are what support this comparison.')],
 faqs=[('Can beard oil fill a patchy beard?','That outcome is not established by this research. Conditioning an existing beard and causing new growth are different claims.'),('Which is best for fragrance avoidance?','We have not verified a fragrance-free option among these six. Several explicitly contain fragrance or named fragrant essential oils. Do not interpret a woody or herbal description as fragrance-free.'),('Is a roll-on the best value?','It has a low initial ₹217 price but contains 10 ml. Ustraa’s checked ₹217 pack contains 35 ml. Compare quantities before treating the bottle price as value.')],
 reference='https://www.aad.org/public/everyday-care/skin-care-secrets/face/healthy-beard', reference_label='AAD: caring for a healthy beard'),
dict(slug='face-wash-for-sensitive-skin', category='skincare', title='Face wash for sensitive skin: two starting points and two conditional alternatives',
 intro='Four retained cleanser records compared honestly: fragrance-free starting points, an uncertain alternative and an active formula that is not the default.',
 opening='Sensitive-feeling skin is not a diagnosis, and a cleanser name cannot predict your tolerance. This guide keeps the four approved cleanser records and separates two verified fragrance-free starting points from two conditional alternatives. We have not added questionable recommendations just to make the count six.',
 selection='Minimalist B12 + Oat leads for its fragrance-free, low-foam positioning, followed by Aquaporin for a fragrance-free foaming preference. Plum Rice Water remains an alternative with fragrance status not verified here. Salicylic + LHA appears last to explain why an active exfoliating cleanser is a different decision, rather than a default sensitive-skin recommendation. This is a cautious suitability sequence, not a clinical safety ranking.',
 items=['minimalist-b12-oat-cleanser','minimalist-aquaporin-cleanser','plum-rice-water-face-wash','minimalist-salicylic-lha-cleanser'],
 education=[('A gentler routine starts with how you wash','AAD guidance recommends a gentle, non-abrasive cleanser, lukewarm water and fingertips rather than scrubbing. More foam, hotter water or a rough cloth is not evidence of a better clean. If your face feels tight after washing, review both your technique and the product instead of adding another exfoliant immediately.'),('Know what the verified labels do and do not mean','B12 + Oat’s stated pH is 5.5–6.5; Aquaporin’s is 5.5. These are manufacturer specifications, not a guarantee against irritation. Fragrance-free status helps identify an excluded ingredient choice but does not establish that every other ingredient will suit you. Read the full current label, particularly if you already know a personal trigger.'),('Do not quietly replace a simple cleanser with an active','Salicylic + LHA has a stated pH of 4.5–5.5 and an active-cleansing position. That does not make it superior for a sensitive-skin brief. If you are using other actives or have a continuing reaction, qualified advice is more useful than combining several shopping recommendations. This guide does not diagnose redness, prescribe treatment or label an unfamiliar formula safe for everyone.')],
 faqs=[('Why are there four products rather than six?','The approved catalog already has these four cleanser records. The six core categories have six products each; this seventh guide is an additional topic. We retain its useful scope without inventing two new sensitive-skin recommendations.'),('Which should I investigate first?','B12 + Oat for the low-foam preference or Aquaporin for the mild-foam preference. Neither is a promise of personal tolerance.'),('Is Plum Rice Water fragrance-free?','That status remains unknown in this research. Do not select it solely on an assumption that a rice-water name implies a fragrance-free formula.')],
 reference='https://www.aad.org/public/everyday-care/skin-care-basics/care/face-washing-101', reference_label='AAD: face washing 101')]

metadata=[]
for g in guides:
    paragraphs=[f'<h2>The decision this guide helps you make</h2><p>{E(g["opening"])}</p>',
       '<h2>How we selected and ordered the recommendations</h2>',f'<p>{E(g["selection"])}</p>',
       '<p>Imagine Utopia’s Glowwise editorial research uses identified manufacturer pages and Indian product listings, checked on 10 October 2026. We have not purchased or personally tested these products. Prices are dated item-price observations, excluding delivery and conditional coupons. The order makes a stated buying preference visible; it is not a hidden numerical score.</p>',
       '<h2>The shortlist at a glance</h2><div class="table-wrap" tabindex="0" role="region" aria-label="Scrollable shortlist"><table class="editorial-table"><caption>Exact first-listed pack; checked 10 October 2026. Stock can change. Swipe or use the keyboard to scroll on narrow screens.</caption><thead><tr><th scope="col">Product / reason</th><th scope="col">Pack</th><th scope="col">INR</th><th scope="col">Verified distinctions</th><th scope="col">Stock at check</th></tr></thead><tbody>']
    for slug in g['items']:
        p=products[slug];v=p['data']['variants'][0];n=notes[slug]
        attrs=p['data']['attributes']
        keys={'sunscreen':['spf','uva-rating','finish','fragrance-free'],'shampoo':['named-ingredients','fragrance-free'],'body-lotion':['named-ingredients','fragrance-free'],'eau-de-parfum':['top-notes','heart-notes'],'beard-trimmer':['model','manufacturer-runtime','charging','cleaning'],'beard-oil':['format','named-ingredients','named-oils','purpose'],'face-cleanser':['texture','ph','fragrance-free']}[p['data']['type']]
        facts='; '.join(k.replace('-',' ')+': '+('Not verified' if attrs.get(k)=='unknown' else attrs[k]) for k in keys if k in attrs)
        stock='Unavailable at check' if any(term in v['availability'].lower() for term in ['out of stock','coming back','sold out']) else 'Listed for purchase'
        paragraphs.append(f'<tr><th scope="row"><a href="/products/{slug}/">{E(p["title"])}</a><br>{E(n["label"])}</th><td>{E(v["label"])}</td><td>₹{v["price"]:g}</td><td>{E(facts)}</td><td>{E(stock)}</td></tr>')
    paragraphs.append('</tbody></table></div><p>Open a product to select another verified pack. An unavailable item’s displayed price is a reference, not an offer. We do not compare grams with millilitres as though they were the same unit.</p>')
    for i,slug in enumerate(g['items'],1):
        p=products[slug];n=notes[slug];d=p['data']
        paragraphs.append(f'<h2>{i}. {E(p["title"])} — {E(n["label"])}</h2>')
        for key in ['reason','advice','tradeoff']:paragraphs.append(f'<p>{E(n[key])}</p>')
        variants='; '.join(f'{v["label"]}: ₹{v["price"]:g}' for v in d['variants'])
        paragraphs.append(f'<p><strong>Checked variants:</strong> {E(variants)}. <a href="/products/{slug}/">Read the complete product record and current stock notes</a>. <a href="{E(d["variants"][0]["source"],quote=True)}" rel="external noopener">'+('View at Tira' if 'tirabeauty.com' in d['source'] else 'View official product')+'</a>.</p>')
    paragraphs.append('<h2>Practical buying guidance</h2>')
    for heading,copy in g['education']:paragraphs.append(f'<h3>{E(heading)}</h3><p>{E(copy)}</p>')
    paragraphs.append('<h2>Common questions</h2>')
    for heading,copy in g['faqs']:paragraphs.append(f'<h3>{E(heading)}</h3><p>{E(copy)}</p>')
    paragraphs.append(f'<h2>Research limits and next steps</h2><p>This is a focused, source-based edit, not an exhaustive survey of the Indian market. Manufacturer efficacy, texture and scent claims remain attributed to the manufacturer. We have not invented customer reviews, measured results or a commercial arrangement. Most product photographs remain unavailable with verified reuse rights; the disclosed fallback is not a photograph of the packaging.</p><p>Visit the <a href="/categories/{g["category"]}/">category directory</a>, use <a href="/finder/?category={g["category"]}">Finder</a> for factual matches and <a href="/compare/">Compare</a> for up to three products of the same type. Save a shortlist in your browser and check the exact pack at the destination before paying. Report a changed fact through <a href="/corrections/">Corrections</a>.</p>')
    paragraphs.append('<h2>Supporting references</h2><ul>')
    if g.get('reference'):paragraphs.append(f'<li><a href="{g["reference"]}" rel="external noopener">{E(g["reference_label"])}</a> — educational guidance, separate from product marketing.</li>')
    for slug in g['items']:paragraphs.append(f'<li><a href="{E(products[slug]["data"]["source"],quote=True)}" rel="external noopener">{E(products[slug]["title"])}: identified product listing</a>, checked 10 October 2026.</li>')
    paragraphs.append('</ul>')
    (ROOT/'content/guides'/f'{g["slug"]}.html').write_bytes(('\n'.join(paragraphs)+'\n').encode('utf-8'))
    metadata.append({k:g[k] for k in ['slug','title','intro','category','items']}|{'checked':'2026-10-10'})
(ROOT/'content/guide-metadata.json').write_bytes((json.dumps(metadata,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
print('Wrote seven original researched guides; preserved canonical identities.')
