"""Update only the two reviewed consent policy records; no runtime or private data."""
import json
from pathlib import Path

path=Path(__file__).resolve().parents[1]/'content/pages.json'
pages=json.loads(path.read_text(encoding='utf-8'))
for page in pages:
    if page['slug']=='privacy':
        page['html']=page['html'].replace('Glowwise does not run an analytics, advertising, session-replay or newsletter service. Contact message text is never added to analytics events. Static resources and licensed fonts are self-hosted.', 'Optional Google Analytics 4 runs only after affirmative consent. We do not run advertising, session replay or a newsletter. Contact message text is never added to analytics events. Static resources and licensed fonts are self-hosted.').replace('Cookie settings record whether you accept an optional analytics preference. No analytics service is currently enabled, so accepting that preference does not start tracking. Rejecting or withdrawing it leaves essential browsing, saved products, comparisons and form security available. Reopen Cookie settings in any footer to change the preference.', 'Cookie settings record your optional analytics choice. Before acceptance, no Google Analytics script, event request or analytics cookie is created by Glowwise. After acceptance, basic page views on recognised editorial, catalog and tool routes use the page title and path. Query strings, referrer URLs, contact/correction pages, search pages and free-text inputs are excluded. Enhanced measurement and advertising signals are off. Google necessarily processes technical connection information under its own <a href="https://policies.google.com/privacy">privacy policy</a>. Analytics cookies expire after 60 days; the property uses two-month user/event retention, while aggregated reports may remain longer. Reopen Cookie settings in any footer to reject or withdraw. Withdrawal removes accessible analytics cookies and reloads the page to unload the SDK. It does not retroactively erase data already received by Google. Essential browsing, saved products, comparisons and form security remain available. An older inactive preference does not activate the new service; a new affirmative choice is required.')
    if page['slug']=='cookies-and-storage':
        page['html']=page['html'].replace('No analytics service is enabled on Glowwise.', 'Optional Google Analytics is off until you affirmatively accept it.').replace('The optional preference is inactive because no analytics provider, cookie or event collection is configured. Choosing acceptance does not send analytics requests or start analytics storage. If an optional service is later introduced, its behaviour and consent requirements must be reviewed first.', 'After acceptance, Google Analytics 4 measures basic page views on recognised editorial, catalog and tool routes. Query strings, referrer URLs, contact/correction pages, search pages and free-text inputs are excluded. Enhanced measurement and advertising signals are off. The _ga and stream-specific _ga cookies expire after 60 days. The property uses two-month user/event retention; aggregated reports may remain longer. Before acceptance or after rejection, Glowwise does not load the SDK or send analytics events.').replace('Essential functionality remains available. Clearing site data', 'Withdrawal removes accessible analytics cookies and reloads the page to unload the SDK. It does not retroactively erase data previously received by Google. Essential functionality remains available. Clearing site data').replace('The protected development installation also requires access authentication. ', '')
# Repeatable disclosure update for the reviewed fixed-name tool events.
for page in pages:
    if page['slug'] in ['privacy','cookies-and-storage'] and 'Tool-use events record only fixed names' not in page['html']:
        page['html']=page['html'].replace('Query strings, referrer URLs, contact/correction pages', 'Tool-use events record only fixed names for finder completion, adding a comparison, saving a product and opening a retailer. They do not include selected products, lists, budgets, answers or free text. Query strings, referrer URLs, contact/correction pages')
path.write_bytes((json.dumps(pages,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
